[workspace]
members = [
    "core",
    "scaii_defs",
    "backends/sky-rts",
]

[profile.release]
codegen-units = 1
lto = true

[patch.crates-io]
specs = {git="https://github.com/LinearZoetrope/specs", branch="saveload-tweak"}