[package]
name = "scaii-core"
version = "0.1.0"
authors = ["Zoe Juozapaitis <jragonmiris@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libloading="0.4.1"
libc = "0.2"
serde = "1.0.14"

# local deps
scaii_defs = {path = "../scaii_defs"}