[package]
name = "scaii-core"
version = "0.1.0"
authors = ["Zoe Juozapaitis <jragonmiris@gmail.com>"]

[features]
default = ["c_api"]

c_api = []
rust_api = []

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
libloading="0.4.1"
prost = "0.2"
libc = "0.2"
lazy_static = "0.2"
websocket="0.20"

# local deps
scaii_defs = {path = "../scaii_defs"}

[profile.release]
#We can't unwind over C boundaries
panic = "abort"