var templateMap = {};
templateMap["stepIntoDecisionPoint"] =  "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,stepIntoDecisionPoint:<DP_NUM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["showQuestion"] =           "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,showQuestion:<SHOW_Q>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["hideEntityTooltips"] =     "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,hideEntityTooltips:<HIDE_TOOL>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["showEntityTooltip"] =      "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,showEntityTooltip:<ENTITY_INFO>_<TIP_QUADRANT>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//CHANGE TARGET for "NA" ALSO????
//templateMap["userClick"] = 				"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;<TARGET>;<TARGET_DTL>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["button-save"] = 			"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:button-save;answerQuestion:<CLCK_DP_NUM>_<USR_TXT_Q1>_<USR_TXT_Q2>_(<USR_CLCK_Q>),<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["expl-control-canvas"] = 	"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:expl-control-canvas;timelineClick:<TIME_LINE_NUM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["decisionPointList"] = 		"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:decisionPointList;jumptToDecisionPoint:<J_DP_NUM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["right-block-div"] = 		"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:right-block-div;clickTimeLineBlocker:<TIME_LINE_BLCKR>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["rewindButton"] = 			"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:rewindButton;rewind:<TIME_LINE_RWND>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["replay-file-selector"] = 	"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:replay-file-selector;touchreReplayFileSelector:<FILE_SLCTR>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["scaii-acronym"] = 			"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:scaii-acronym;touchAcronym:<TCH_ACRONYM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["game-replay-label"] = 		"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:game-replay-label;touchReplayingGamefileLabel:<RPL_GAME_FILE>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["gameboardBackground"] = 	"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:gameboardBackground;clickGameQuadrant:<CLCK_QUADRANT>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
//templateMap["gameboard"] = 				"<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:gameboard;clickEntity:<CLCK_GAME_ENTITY>_<CLCK_QUADRANT>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";

//logTemplate.js
templateMap["userClick"] =              "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;<TARGET>;<TARGET_DTL>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["button-save"] =            "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;answerQuestion:<CLCK_STEP>.<Q_INDEX_STEP>_<USR_TXT_Q1>_<USR_TXT_Q2>_(<USR_CLCK_Q>),<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["expl-control-canvas"] =    "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;timelineClick:<TIME_LINE_NUM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["decisionPointList"] =      "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;jumpToDecisionPoint:<J_DP_NUM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["right-block-div"] =        "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;clickTimeLineBlocker:<TIME_LINE_BLCKR>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["rewindButton"] =           "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;rewind:<TIME_LINE_RWND>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["replay-file-selector"] =   "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;touchreReplayFileSelector:<FILE_SLCTR>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["scaii-acronym"] =          "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;touchAcronym:<TCH_ACRONYM>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["game-replay-label"] =      "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;touchReplayingGamefileLabel:<RPL_GAME_FILE>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["game-replay-label-selector"] =      "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;touchReplayingGamefileSelector:<RPL_GAME_SLCTR>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["touch-step-progress-label"] =      "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;touchStepProgressLabel:<RPL_GAME_PRGSS>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["gameboardBackground"] =    "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;clickGameQuadrant:<CLCK_QUADRANT>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";
templateMap["gameboard"] =              "<DATE>,<TIME>,<1970_SEC>,<DP>,<Q_ID>,userClick:<COORD_X>_<COORD_Y>;region:<REGION>;target:<TARGET>;clickEntity:<CLCK_GAME_ENTITY>_<CLCK_QUADRANT>,<CMB_RWRD>,<DTL_RWRD>,<CMB_ADV>,<DTL_ADV>,<CMB_SALNCY>,<DTL_SALNCY>";